services:
  api:
    image: ghcr.io/siahmurph/pathfinder-api:latest
    container_name: pathfinder-api
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - /opt/apps/pathfinder/data:/app/data
    environment:
      - ROOT_PATH=/pathfinder/api
      - DB_PATH=/app/data/pathfinder.db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    image: ghcr.io/siahmurph/pathfinder-frontend:latest
    container_name: pathfinder-frontend
    restart: unless-stopped
    ports:
      - "8006:80"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
