version: '3.8'

services:
  api:
    image: ghcr.io/siahmurph/pathfinder-api:latest
    container_name: pathfinder_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - pathfinder_data:/app/data
    environment:
      - ROOT_PATH=/api
      - DB_PATH=/app/data/pathfinder.db

  frontend:
    image: ghcr.io/siahmurph/pathfinder-frontend:latest
    container_name: pathfinder_frontend
    restart: always
    ports:
      - "8006:80"

volumes:
  pathfinder_data: