version: '3.8'

services:
  api:
    image: ghcr.io/siahmurph/pathfinder-api:latest
    container_name: pathfinder_api
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - /opt/apps/pathfinder/data:/app/data
    environment:
      - ROOT_PATH=/pathfinder/api
      - DB_PATH=/app/data/pathfinder.db

  frontend:
    image: ghcr.io/siahmurph/pathfinder-frontend:latest
    container_name: pathfinder_frontend
    restart: unless-stopped
    ports:
      - "8006:80"
