version: '3.8'

services:
  api:
    image: ghcr.io/siahmurph/parouter-op-api:latest
    container_name: parouter_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - parouter_data:/app/data
    environment:
      - ROOT_PATH=/api
      - DB_PATH=/app/data/ROUTES.db

  frontend:
    image: ghcr.io/siahmurph/parouter-op-frontend:latest
    container_name: parouter_frontend
    restart: always
    ports:
      - "8006:80"

volumes:
  parouter_data: