name: Build and Publish Docker Image

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  security-events: write


jobs:
  build-and-publish:
    uses: siahmurph/devops-templates/.github/workflows/docker-build-publish.yml@main
    with:
      image_name: vanmanager
      dockerfile_path: ./Dockerfile
      context_path: .
    secrets: inherit
